net:
  jqsoft:
    constants: #系统属性配置
      init-password: 123456 #默认用户初始密码
      upload-path: D:/upload/babyservice #上传文件存放路径
    datasource: #数据源配置（这里是正式库的地址）
      driver-class-name: com.mysql.jdbc.Driver
      #      url: jdbc:mysql://192.168.44.113:3306/babyservice?useUnicode=true&characterEncoding=utf8
      url: jdbc:mysql://10.1.55.3:3306/babyservice?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      validationQuery: SELECT 1 FROM DUAL
    mybatis: #mybatis配置
      dialect: mysql #分页方言  oracle/mysql
      id-type: 3   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      mapper-locations: classpath:mapper/*.xml #映射地址
      type-aliases-package: com.jqsoft.babyservice.entity #实体包
      # 以下 开发环境使用，线上不推荐，上线时将refresh-mapper和trace置为false,或删除配置项
      refresh-mapper: true #刷新mapper 调试神器
      trace: true #执行性能分析和SQL格式化打印
      sql-max-execute-time: 5000 #指的是sql最大执行时长,超时抛异常说明SQL效率有问题,单位毫秒

#----------------------     日志配置        -----------------------
logging:
  path: D:/logs/babyservice #日志文件目录

spring:
  # 缓存配置
  redis:
    # 地址
    host: localhost
    # 连接端口
    port: 6379
    # 数据库索引（默认为0）
    database: 0
    # 连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    protocol: smtp
    username: babyservice@163.com
    password: nposervice2019
    nick: 社管通
    smtp:
      auth: true
      starttls:
        enable: true
        required: true

# 登录token redis过期时间(分钟)
token-expire: 43200
# 普通数据redis过期时间（分钟）
value-expire: 1440

# 对象存储
oss.key: LTAItjiLek75VbJA
oss.secret: ijLrOxVdpXUO6lyHJek8c5N15fdpPv
oss.url: https://oss-cn-shanghai.aliyuncs.com
oss.bucket: npo-test
oss.endpoint: http://npo-test.oss-cn-shanghai.aliyuncs.com/

#http回调方式需要的参数
#env.token: sheguantong
#env.encoding_aes_key: 8ncwz3527xf45pxntlbdkoresww03tmd8ivkjb7mlhx
#env.suite_key: suite7ugjye1ll5cwudii
#env.suite_secret: mxIV_NzNuJggZ8I6uk0yiykg7PYEIQ5cEkvm97dmNhYVoEwzojlVdBXgk7m13YV1
#env.appid: 27831

#钉钉云推送方式需要的参数
env.suite_key: suitenhxcjt7akqrcy5jg
env.suite_secret: 3RJOdpLzvVuKz5dLJNBhIsS9OKXjzZz5LQBLgtrwMZnTQMLBWZgGnxitzds7LJxg
env.appid: 27425