net:
  jqsoft:
    constants: #系统属性配置
      init-password: 123456 #默认用户初始密码
      upload-path: D:/upload/nposervice #上传文件存放路径
    datasource: #数据源配置（这里是正式库的地址）
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.44.113:3306/nposervice?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      validationQuery: SELECT 1 FROM DUAL
    mybatis: #mybatis配置
      dialect: mysql #分页方言  oracle/mysql
      id-type: 3   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      mapper-locations: classpath:mapper/*.xml #映射地址
      type-aliases-package: com.jqsoft.nposervice.entity #实体包
      # 以下 开发环境使用，线上不推荐，上线时将refresh-mapper和trace置为false,或删除配置项
      refresh-mapper: false #刷新mapper 调试神器
      trace: false #执行性能分析和SQL格式化打印
      sql-max-execute-time: 5000 #指的是sql最大执行时长,超时抛异常说明SQL效率有问题,单位毫秒
    shiro: #shiro配置
      auth-cache-enabled: true
      jcaptcha-enable: false #开发环境下将其设置为false,不启用验证码 方便调试
      login-url: /login
      login-success-url: /index
      filte-rules:
        - /dist/**,/layui/**,/tips/**,/image/**,/home.**,/layout.**,/mgt/**,/third_party/**-->anon
        - /user/**-->anon
        - /login/**-->authc
        - /logout/**-->logout
        - /**-->anon

#----------------------     日志配置        -----------------------
logging:
  path: D:/logs/nposervice #日志文件目录