#----------------------     特别说明        ----------------------- 
# 　属性顶格写，不能有空格
#  缩进一定不能使用"tab"制表符,使用两个空格进行缩进，否则在linux下会有各种奇怪的问题，有可能使项目无法启动
# 　属性和值之间的"冒号"后面需要有空格
#----------------------     系统配置        -----------------------

#----------------------     WEB容器配置        -----------------------  
server:
  port: 8080 #端口
#  servlet:
#    context-path: / #路径上下文
#    jsp:
#      init-parameters: #jsp支持热部署
#        development: true
#----------------------     SPRING配置        ----------------------- 
spring:
  profiles:
    active: dev # dev 为开发环境，test 为开发环境，上线时把此项属性注释掉,切记
  application:
    name: 宝宝健康体检 #系统名称
  devtools:
    restart:
      enabled: true #启用热启动
  freemarker:
    request-context-attribute: request
    expose-request-attributes: true
    suffix: .html  #后缀名
    content-type: text/html
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    expose-session-attributes: true
    check-template-location: true
    templateEncoding: UTF-8
    enabled: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
app:
  key: dingrd4sjd5px5sewf65
  secret: 5G8pjSWoTRgKSbYpbNd2Tvl3VM_TefWheCoaNjTkfc5ZPGeWFTkm51koHIXFvftE