#************************************* database config ************************************************
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://132.232.31.240:3306/babyservice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#spring.datasource.url: jdbc:mysql://30.40.42.153:3306/babyservice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.initialSize: 16
spring.datasource.minIdle: 8
spring.datasource.maxActive: 32
spring.datasource.maxWait: 1000
spring.datasource.timeBetweenEvictionRunsMillis: 6000
spring.datasource.minEvictableIdleTimeMillis: 30000
spring.datasource.validationQuery: SELECT 'OK'
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat,wall,log4j
spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 3000

#************************************* redis config ************************************************
spring.redis.host: 132.232.31.240
#spring.redis.host: 30.40.42.153
spring.redis.database: 0
spring.redis.port: 6379
spring.redis.password: 123456
spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-wait: -1
spring.redis.jedis.pool.max-idle: 8
spring.redis.jedis.pool.min-idle: 0
spring.redis.timeout: 5000

#************************************* log config ************************************************
logging.level.ROOT: INFO
logging.level.org.springframework.web: INFO
logging.level.com.jqsoft.babyservice: INFO
#logging.pattern.console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n
#logging.pattern.file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file: /Users/admin/logs/babyservice.log
logging.level.com.jqsoft.babyservice.mapper.biz: debug

#************************************* mybatis config ************************************************
mybatis.type-aliases-package: com.jqsoft.babyservice.entity.biz
mybatis.mapperLocations: classpath:mapper/*.xml

# 登录token redis过期时间(分钟)
token-expire: 43200
# 普通数据redis过期时间（分钟）
value-expire: 1440

#业务事件回调需要的参数
env.token: 123456
env.aes_key: xxxxxxxxlvdhntotr3x9qhlbytb18zyz5zxxxxxxxxx
env.key: dinge3e211ad45c983df35c2f4657eb6378f
env.domain: http://baby.vaiwan.com

#************************************* job cron config ************************************************
# 每天下午3点定时发送钉钉提醒消息
job.cron.remindNewsJob: 0 0 15 * * ?

dd.app.agentId: 316969988

#************************************* remind template config ************************************************
remind.template0: 家长您好！宝宝已到%s了，请您明天带上宝宝，到社区服务中心进行%s体检，祝宝宝健康成长。
remind.template1: 家长您好！请在宝宝%s体检完成后，在系统中即时点击签到按钮，祝宝宝健康成长。
remind.template2: 家长您好！宝宝已到%s啦。如果%s已体检完成，请您点击下方按钮进行体检签到。如果还未体检，请您明天带上宝宝到社区服务中心进行体检，祝宝宝健康成长。

#************************************ system config *********************************************
hospitalName: 闻堰社区卫生服务中心
welcomeNewsTitle: 欢迎使用宝宝健康体检
welcomeNewsContext: 家长您好！欢迎使用宝宝健康体检！您可以点击左下角“宝宝管理”，查看您的宝宝信息。快去试一试吧！
